export const shopcategory = [
    "Grocery & Food",
    "Clothing & Fashion",
    "Electronics & Appliances",
    "Home & Furnishing",
    "Beauty & Personal Care",
    "Jewelry & Accessories",
    "Health & Wellness",
    "Books & Stationery",
    "Automotive",
    "Toys & Baby Products",
    "Sports & Outdoor",
    "Hardware & Building Materials",
    "Pet Supplies",
    "Footwear & Accessories",
    "Gifts & Flower Shops",
    "Restaurants & Food Services",
    "Entertainment & Hobbies",
    "Travel & Tourism",
    "Repair & Service Shops",
    "Handicrafts & Traditional Goods",
    " Eco-friendly & Sustainable Products",
    "Technology & Gadgets",
    "Wedding & Event Planning",
    "Festivals & Seasonal Shops",
    "Travel Accessories",
    "Luxury Goods",
    "Religious & Spiritual Goods",
    "Green Energy & Solar Products",
    "Education & Coaching Centers",
    "Art & Cultural Stores",
    "Alcohol & Beverages",
    "Local Markets & Bazaars",
    "Other",
  ];