export const LOCK_FEATURE_REQUEST = "LOCK_FEATURE_REQUEST";
export const LOCK_FEATURE_SUCCESS = "LOCK_FEATURE_SUCCESS";
export const LOCK_FEATURE_FAIL =    "LOCK_FEATURE_FAIL";
export const LOCK_FEATURE_RESET =    "LOCK_FEATURE_RESET";

export const UNLOCK_FEATURE_REQUEST = "UNLOCK_FEATURE_REQUEST";
export const UNLOCK_FEATURE_SUCCESS = "UNLOCK_FEATURE_SUCCESS";
export const UNLOCK_FEATURE_FAIL =    "UNLOCK_FEATURE_FAIL";
export const UNLOCK_FEATURE_RESET =    "UNLOCK_FEATURE_RESET";

export const GET_LOCK_LIST_REQUEST = "GET_LOCK_LIST_REQUEST";
export const GET_LOCK_LIST_SUCCESS = "GET_LOCK_LIST_SUCCESS";
export const GET_LOCK_LIST_FAIL =    "GET_LOCK_LIST_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS"; 